#!/bin/sh

# Modifers
mod="Mod1"
win="Mod4"

# Autostart variables
notifs="mako"
outputConfig="kanshi"
terminalServer="foot --server"
screenShare="/usr/lib/xdg-desktop-portal-wlr"
keyringDaemon"gnome-keyring-daemon --start"
wallpaperSetter="swaybg -i ~/Downloads/digital-art-sea-pixel-art-rock-snow-winter-569370-wallhere.com.jpg"

# Keybid variables
statusbar="amber"
terminal="footclient"
nightLight="wlsunset -T 4500"
copyScreenshot="grimshot --notify copy area"
saveScreenshot="grimshot --notify save"
copyArea="grimshot --notify copy area"
editScreenshot="grim - | swappy -f -"

# Theme variables
innerFocus="#A093C7"
innerUnFocus="#3E445E"
outerFocus="#161821"
outerUnFocus="#161821"
innerWidth=2
outerWidth=9
bgColor="#1E2132"

# Autostart
riverctl spawn $notifs
riverctl spawn $outputConfig
riverctl spawn $terminalServer
riverctl spawn $screenShare
riverctl spawn $keyringDaemon
riverctl spawn $wallpaperSetter

# River settings
riverctl set-repeat 50 300
riverctl float-filter-add "float"
riverctl float-filter-add "popup"
riverctl focus-follows-cursor normal
riverctl opacity 1.0 1.0 0.0 0.1 20
riverctl map normal $mod+Shift E exit

# River theme settings
riverctl inner-color-focused $innerFocus
riverctl inner-color-unfocused $innerUnFocus
riverctl inner-width $innerWidth
riverctl outer-color-focused $outerFocus
riverctl outer-color-unfocused $outerUnFocus
riverctl outer-width $outerWidth
riverctl background-color $bgColor
riverctl opacity 1.0 1.0 0.0 0.1 20

# Bind apps and tools
riverctl map normal $mod Return spawn $terminal
riverctl map normal $mod W spawn $nightLight
riverctl map normal $mod B spawn $statusbar
riverctl map normal $mod+Shift B spawn 'pkill ${statusbar}'
riverctl map normal None print spawn $copyScreenshot
riverctl map normal $mod+Shift print spawn $saveScreenshot
riverctl map normal $win+Shift print spawn $editScreenshot

# View control
riverctl map normal $mod Z zoom
riverctl map normal $mod+Shift Q close
riverctl map normal $mod Space toggle-float
riverctl map normal $mod F toggle-fullscreen
riverctl map normal $win+Shift J swap next
riverctl map normal $win+Shift K swap previous
riverctl map normal $win+Mod1+Control H snap left
riverctl map normal $win+Mod1+Control J snap down
riverctl map normal $win+Mod1+Control K snap up
riverctl map normal $win+Mod1+Control L snap right
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous
riverctl map normal $win+$mod H move left 100
riverctl map normal $win+$mod J move down 100
riverctl map normal $win+$mod K move up 100
riverctl map normal $win+$mod L move right 100
riverctl map normal $win+Mod1+Shift H resize horizontal -100
riverctl map normal $win+Mod1+Shift J resize vertical 100
riverctl map normal $win+Mod1+Shift K resize vertical -100
riverctl map normal $win+Mod1+Shift L resize horizontal 100
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view


# Setup 5 tags and keybinds for them
for i in $(seq 1 5)
do
    tags=$((1 << ($i - 1)))
    riverctl map normal $mod $i set-focused-tags $tags
    riverctl map normal $mod+Shift $i set-view-tags $tags
    riverctl map normal $mod+Control $i toggle-focused-tags $tags
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# Layouting
riverctl map normal $mod+Shift H mod-layout-value rivertile int main_count +1
riverctl map normal $mod+Shift L mod-layout-value rivertile int main_count -1
riverctl map normal $mod H mod-layout-value rivertile fixed main_factor -0.05
riverctl map normal $mod L mod-layout-value rivertile fixed main_factor +0.05
riverctl map normal $mod Up    set-layout-value rivertile string main_location top
riverctl map normal $mod Right set-layout-value rivertile string main_location right
riverctl map normal $mod Down  set-layout-value rivertile string main_location bottom
riverctl map normal $mod Left  set-layout-value rivertile string main_location left

# Passthrough for media keybinds
riverctl declare-mode passthrough
riverctl map normal $mod F11 enter-mode passthrough
riverctl map passthrough $mod F11 enter-mode normal

for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn pamixer -i 5
    riverctl map $mode None XF86AudioLowerVolume  spawn pamixer -d 5
    riverctl map $mode None XF86AudioMute         spawn pamixer --toggle-mute
    riverctl map $mode None XF86MonBrightnessUp   spawn light -A 5
    riverctl map $mode None XF86MonBrightnessDown spawn light -U 5
done

# Setuo default layout and padding
riverctl default-layout rivertile
exec rivertile -view-padding 10 -outer-padding 12
