require("settings.popups.menubar")
require("settings.popups.naughty")
require("settings.decorations.titlebar")
require("settings.general.autostart")
require("settings.general.keybinds")
require("settings.rules.clients")
require("settings.rules.notifs")
require("settings.windows.placement")
